kind: Service
apiVersion: v1
metadata:
  name: react-web-service
spec:
  selector:
    app: react-web
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-react-app
  labels:
    app: react-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-web
  template:
    metadata:
      labels:
        app: react-web
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: react-web
        image: ${CICD_IMAGE}:${CICD_PIPELINE_ID}-${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 80
## Ingress example
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: react-web
spec:
  rules:
  - host: react-web.172.31.0.179.nip.io
    http:
      paths:
      - backend:
          serviceName: react-web-service
          servicePort: 80